package Exception.ExceptionInFunction;

public class TIPS {
    /*
    * 该实验证明：
    * 如果在方法中有循环
    * 该循环中会产生抛出异常的情况
    * 那么该方法的循环在抛出异常后停止循环，即该方法结束。
    *
    * 所以在方法中如果使用抛出异常的方法的时候注意不要使用循环
    *
    * */
}
